
################################################################################################
############ based on code from:
############ https://github.com/Brideau/GeospatialLineGraphs/blob/master/02PlotDataPeaks.R 
################################################################################################

library(graphics)
library(tcltk)
library(pracma)
library(tidyverse)

# Load the data generated by 01GenerateData.R
plot.data <- read_csv("./data/GeneratedData/HydroLakes0.5_Area.csv")
filename = 'HydroLakes0.5_Area'
# plot.data <- read_csv("./data/GeneratedData/HydroLakes_CentroidCount.csv")
# filename = 'HydroLakes_CentroidCount'

# Add padding above/below where there was data
# On top
top.padding <- 1:1
for (i in top.padding) {
  plot.data <- cbind(0, plot.data)
}
# On bottom
bottom.padding <- 1:1
for (i in bottom.padding) {
  plot.data <- cbind(plot.data, 0)
}

# On left
zero.row <- vector(mode="integer", length=dim(plot.data)[1])

left.padding <- 1:10
for (i in left.padding) {
  plot.data <- rbind(zero.row, plot.data)
}

# On right
right.padding <- 1:10
for (i in left.padding) {
  plot.data <- rbind(plot.data, zero.row)
}

################################
############ AS PNG ############
################################

png(filename = paste0("./figures/",filename,".png"), width = 12,height = 9, units = 'in',res = 500)

par(mar=c(0,0,0,0))

max <- max(plot.data) # Max value in the data, used for scaling
plottingHeight <- 1000 # Arbitrary number that provides the graph's height
scaleFactor <- 200 # Discovered through trial and error to keep the graph in the boundaries (original = 300)
gap <- plottingHeight / length(plot.data) # Space between lines


# Create a blank plot
yVals <- as.vector(plot.data[[1]] / max * scaleFactor)
plot(0, 0, xlim=c(0, length(yVals)), ylim=c(0,1100), type="n", las=1, xlab=NA, ylab=NA, bty="n", axes=F)

plotting.threshold <- 0.1

plot.length = length(plot.data)

# Plot each line
for (i in 1:(plot.length-30)) {
  # Grabs a row of data
  yVals <- as.vector(plot.data[[i]] / max * scaleFactor)
  xVals <- c(0:(length(yVals) - 1))
  yVals.smooth =  savgol(yVals, 3, forder=4)
  
  polygon(xVals, yVals.smooth + plottingHeight, border = NA, col = "#ffffff")
  lines(xVals, yVals.smooth + plottingHeight, col="grey50", lwd=0.3)
  
  #Plot the peaks with a darker line.
  j <- 2 # Skip padding
  while (j <= (length(yVals.smooth) - 2)) {
    
    if ((yVals.smooth[j]) > plotting.threshold | (yVals.smooth[j+1]) > plotting.threshold) {
      segments(xVals[j], yVals.smooth[j] + plottingHeight, xVals[j+1], yVals.smooth[j+1] + plottingHeight, col="grey10", lwd=1)
    } else { } # Do nothing
    
    j <- j + 1
    
  }
  plottingHeight <- plottingHeight - gap
  
}
title(main = "Global Lake Density   ",
      sub = "Data: HydroLakes, Code: https://github.com/hdugan/LakeDensityViz              ",
      line = -4, adj=1, cex.main = 3, cex.sub = 0.7)

dev.off()


